### ISSUE TITLE
Pickaxes not working while mod installed

### ISSUE THREAD

**Issue by sophiec0de** [awesomeshot5051/MobFarms#1] opened 2024-10-07 23:09 UTC
While the mod is installed, pickaxes no longer break normal blocks and instead act like a fist. Blocks take a long time to break and do not drop any items. For example, trying to mine a block of gold ore takes several seconds and does not yield any gold ore.

**Comment by awesomeshot5051** [comment] 2024-10-07 23:13
Can you send me a video?

**Comment by awesomeshot5051** [comment] 2024-10-07 23:33
https://drive.google.com/file/d/1BXhW-z31rLyMTk6Do1QQBkpYkHOaZSde/view?usp=sharing

This is with nothing, but my mod loaded.

**Comment by sophiec0de** [comment] 2024-10-08 00:01
https://drive.google.com/file/d/1vu5sVYgySpXStM1H7-D0eC2Zm1xYVjws/view?usp=drive_link

It only happens when this mod is enabled, it's either an incompatibility with another mod I have or there is a dependency missing but I can't see a list of dependencies to make sure I have the correct ones installed.

**Comment by awesomeshot5051** [comment] 2024-10-08 00:18
When you're posting a link to a video please ensure the proper access is given.

**Comment by sophiec0de** [comment] 2024-10-08 00:22
Access has been granted, my apologies, I've never shared from drive before,
you could try responding more politely though since I am trying to help you
fix your mod.

**Comment by awesomeshot5051** [comment] 2024-10-08 00:25
Have you tried loading without my mod loaded.
Have you tried loading with ONLY my mod loaded.
I notice a message from EnderIO that it's in alpha mode. 
There could be a problem with that mod. 
I'm not saying that there isn't anything wrong with my mod, there's a lot of bugs I still have to iron out, but I'm running it on my machine with 90+ mods and it works just fine. And it runs with only my mod loaded just fine as well.
There are no dependencies, as they are included within the mod.

**Comment by sophiec0de** [comment] 2024-10-08 01:06
After going through all the mods, the conflict is with Iris Shaders. Mining
works fine unless iris shaders is installed.

**Comment by awesomeshot5051** [comment] 2024-10-08 01:14
Is it that it works when both Iris Shaders and Mob Farms is installed? Or just Iris Shaders? 
I don't know of any conflicts. 
If it's just Iris Shaders, I would open an issue on their GitHub and close this one.

**Comment by sophiec0de** [comment] 2024-10-08 01:47
Mining doesn't work only when both Iris Shaders and Mob Farms are
installed, but works when either one of them isn't installed. So the issue
is somewhere your mod and Iris Shaders are conflicting to prevent mining,
Since Iris Shaders is so popular it's something you should look in to.

**Comment by awesomeshot5051** [comment] 2024-10-08 02:08
I think the issue is the fact that I use a custom renderer for my mod. Unfortunately, because so much of my mod depends on this custom renderer, I will not be changing it. However, I would like to note that on the Iris Shaders page, it does say:
"Fixed support for some packs that did not work correctly on Iris 1.7.x. (Some packs such as KappaPT are currently broken for an unknown reason; this is being investigated.)"
so, it's completely that this issue will be fixed in the next update of Iris. Until then, I would uninstall my mod. I'm sorry that I couldn't help you anymore. I'm closing this issue since the problem lies with compatibility between the two mods in a way that I'm unable to fix, at least for the moment.

**Comment by awesomeshot5051** [comment] 2024-10-08 23:54
I have fixed this bug. It should work with Iris Shaders now. I'm sorry for the problem it caused. If you have anymore issues, let me know.

**Comment by sophiec0de** [comment] 2024-10-08 23:58
Thanks.

**Closed** 2024-10-16 17:26 UTC
Labels: bug
